cursor #ebe1d4
cursor_text_color #d0c5b4

foreground            #ebe1d4
background            #17130b
selection_foreground  #000000
selection_background  #ffd54f
url_color             #ffc107

color0   #17130b
color1   #ff1b02
color2   #2aff07
color3   #ffd500
color4   #f2b500
color5   #765800
color6   #ffc107
color7   #fff7e1
color8   #a59f8d
color9   #ff5545
color10  #6aff51
color11  #ffe251
color12  #ffca2c
color13  #ffd351
color14  #ffe38f
color15  #fffbf2
