color0   #101417
color1   #d65555
color2   #339031
color3   #a47852
color4   #2487b5
color5   #7da0b9
color6   #94cdf7
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #54a552
color11   #b08b69
color12   #84caff
color13   #2a828f
color14   #38698e
color15   #ffffff

cursor #dfe3e8
cursor_text_color #c1c7ce

foreground            #dfe3e8
background            #101417
selection_foreground  #21323f
selection_background  #b7c9d9
url_color             #94cdf7