shell fish


font_family JetBrainsMono Nerd Font Mono
font_size 13.0

bold_font auto
italic_font auto
bold_italic_font auto


# Arabic font as fallback
symbol_map U+0600-U+06FF Noto Sans Arabic
disable_ligatures never

#background_opacity 0.8
dynamic_background_opacity 1
confirm_os_window_close 0
hide_window_decorations yes

# Animated cursor
cursor_trail 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4
# selection_foreground none
# selection_background none
# foreground #dddddd
# background #000000
# cursor #dddddd

# BEGIN_KITTY_THEME
# Kaolin Aurora
include decay.conf
# END_KITTY_THEME
#include dank-theme.conf

#: tab details
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled

# vim-style window navigation
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up

# splits
enabled_layouts splits
map ctrl+shift+\ launch --location=vsplit
map ctrl+shift+x launch --location=hsplit

# quick tab switching by number
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
