# vim:ft=kitty

## name: Decay (modified into Kaolin Aurora structure)
## source: https://github.com/decaycs

# The basic colors
foreground              #b6beca
background              #171a1f
selection_foreground    #a9b1d6
selection_background    #22262e

# Cursor colors
cursor                  #f5f5f5
cursor_text_color       #a9b1d6

# kitty window border colors
active_border_color     #74bee9
inactive_border_color   #384148

# Tab bar colors
active_tab_background   #dee1e6
active_tab_foreground   #171a1f
inactive_tab_background #384148
inactive_tab_foreground #171a1f

# black
color0    #1c252c
color8    #384148

# red
color1    #e05f65
color9    #fc7b81

# green
color2    #78dba9
color10   #94f7c5

# yellow
color3    #f1cf8a
color11   #ffeba6

# blue
color4    #70a5eb
color12   #8cc1ff

# magenta
color5    #c68aee
color13   #e2a6ff

# cyan
color6    #74bee9
color14   #90daff

# white
color7    #dee1e6
color15   #fafdff

